import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import Logo from '../components/Logo';
import { getCurrentUser } from '../services/authService';
import { deleteLeague, getLeagueSettingsData, leaveLeague, removeLeagueMember, saveLeagueScoring } from '../services/leagueService';

const POINT_FIELDS = [['exact', 'settings.points.exact'], ['winnerOne', 'settings.points.winnerOne'], ['winnerOnly', 'settings.points.winnerOnly']];

export default function LeagueSettings() {
  const { ligaId } = useParams(); const navigate = useNavigate(); const { t } = useTranslation();
  const [settings, setSettings] = useState(null); const [points, setPoints] = useState({ exact: 3, winnerOne: 2, winnerOnly: 1 }); const [confirmName, setConfirmName] = useState(''); const [loading, setLoading] = useState(true); const [processing, setProcessing] = useState(false); const [error, setError] = useState(false);
  useEffect(() => { if (!ligaId || Number.isNaN(Number(ligaId))) { navigate('/home'); return; } const load = async () => { setLoading(true); try { const user = await getCurrentUser(); if (!user) { navigate('/'); return; } const data = await getLeagueSettingsData(ligaId, user.id); if (!data.isAdmin && !data.membershipId) { window.alert(t('settings.messages.notMember')); navigate('/home'); return; } setSettings(data); setPoints(data.points); } catch (loadError) { console.error('Unable to load league settings', loadError); setError(true); } finally { setLoading(false); } }; load(); }, [ligaId, navigate, t]);
  const save = async () => { setProcessing(true); try { await saveLeagueScoring(settings.id, points); window.alert(t('settings.messages.saved')); } catch (saveError) { console.error('Unable to save league scoring', saveError); window.alert(t('settings.messages.saveError')); } finally { setProcessing(false); } };
  const removeMember = async (member) => { if (member.role?.toLowerCase() === 'admin' || !window.confirm(t('settings.messages.removeConfirm', { name: member.users?.name ?? '' }))) return; try { await removeLeagueMember(member.id); setSettings((current) => ({ ...current, members: current.members.filter((item) => item.id !== member.id) })); } catch { window.alert(t('settings.messages.removeError')); } };
  const leave = async () => { if (!window.confirm(t('settings.messages.leaveConfirm'))) return; setProcessing(true); try { await leaveLeague(settings.membershipId); navigate('/home'); } catch { window.alert(t('settings.messages.leaveError')); } finally { setProcessing(false); } };
  const destroy = async () => { if (confirmName !== settings.name) { window.alert(t('settings.messages.nameMismatch')); return; } if (!window.confirm(t('settings.messages.deleteConfirm', { name: settings.name }))) return; setProcessing(true); try { await deleteLeague(settings.id); navigate('/home'); } catch { window.alert(t('settings.messages.deleteError')); } finally { setProcessing(false); } };
  if (loading) return <State label={t('settings.loading')} />; if (error || !settings) return <State label={t('settings.messages.loadError')} />;
  return <div className="min-h-screen bg-[#0A0E2A] text-white p-6 font-sans pb-20"><header className="mb-10 mt-4 flex items-center gap-4 max-w-lg mx-auto"><Link to={`/predictions/${ligaId}`} className="bg-[#1A1C3A] px-4 py-2 rounded-xl text-[10px] font-black italic border border-[#26283A]">← {t('common.back')}</Link><Logo size="sm" /><h1 className="text-2xl font-black italic uppercase tracking-tighter">{t('settings.title')}</h1></header><main className="max-w-lg mx-auto space-y-6">{settings.isAdmin && <section className="bg-[#1A1C3A] p-8 rounded-[40px] border border-[#26283A] shadow-2xl"><h2 className="font-black italic uppercase text-sm text-[#0077FF] mb-2">{t('settings.scoring.title')}</h2><p className="text-xs text-gray-400 mb-6">{t('settings.scoring.description')}</p><div className="grid grid-cols-3 gap-2 py-4 border-y border-[#26283A] mb-6">{POINT_FIELDS.map(([key, label]) => <label key={key} className="text-center"><span className="block text-[7px] font-black uppercase mb-2 opacity-50">{t(label)}</span><input type="number" min="0" value={points[key]} onChange={(event) => setPoints((current) => ({ ...current, [key]: event.target.value }))} className="w-full bg-[#0A0E2A] border border-[#26283A] rounded-xl p-3 text-center font-black text-[#0077FF] outline-none" /></label>)}</div><button onClick={save} disabled={processing} className="w-full bg-[#0077FF] py-4 rounded-2xl font-black text-sm uppercase">{processing ? t('settings.saving') : t('settings.scoring.save')}</button></section>}<Members members={settings.members} isAdmin={settings.isAdmin} onRemove={removeMember} t={t} />{settings.isAdmin ? <DeleteZone name={settings.name} value={confirmName} setValue={setConfirmName} disabled={processing || confirmName !== settings.name} onDelete={destroy} t={t} /> : <LeaveZone disabled={processing} onLeave={leave} t={t} />}</main></div>;
}
function Members({ members, isAdmin, onRemove, t }) { return <section className="bg-[#1A1C3A] p-6 rounded-[35px] border border-[#26283A]"><h2 className="font-black italic uppercase text-sm mb-4 text-[#0077FF]">{t(isAdmin ? 'settings.members.manage' : 'settings.members.title')}</h2><div className="space-y-3">{members.map((member) => <div key={member.id} className="bg-[#0A0E2A] border border-[#26283A] p-4 rounded-2xl flex justify-between items-center"><div><span className="block font-bold text-xs uppercase">{member.users?.name ?? t('settings.members.unknown')} {member.role?.toLowerCase() === 'admin' && <span className="text-[#0077FF] ml-2 text-[9px] font-black">{t('settings.members.admin')}</span>}</span><span className="text-[10px] text-gray-500">{member.users?.email}</span></div>{isAdmin && member.role?.toLowerCase() !== 'admin' && <button onClick={() => onRemove(member)} className="text-gray-400 px-3 py-1.5 rounded-xl text-[10px] font-black uppercase border border-[#26283A]">{t('settings.members.remove')}</button>}</div>)}</div></section>; }
function DeleteZone({ name, value, setValue, disabled, onDelete, t }) { return <section className="bg-[#1A1C3A] p-6 rounded-[35px] border border-[#FF3333]/30 text-center"><h2 className="font-black italic uppercase text-sm mb-2 text-[#FF3333]">{t('settings.danger.adminTitle')}</h2><p className="text-xs text-gray-400 mb-4">{t('settings.danger.deleteDescription', { name })}</p><input value={value} onChange={(event) => setValue(event.target.value)} placeholder={name} className="w-full bg-[#0A0E2A] border border-[#26283A] rounded-xl p-3 text-center font-bold text-white outline-none text-xs mb-3" /><button onClick={onDelete} disabled={disabled} className="w-full bg-[#FF3333] disabled:opacity-20 text-white py-4 rounded-2xl font-black text-xs uppercase">{t('settings.danger.delete')}</button></section>; }
function LeaveZone({ disabled, onLeave, t }) { return <section className="bg-[#1A1C3A] p-6 rounded-[35px] border border-[#FF3333]/30 text-center"><h2 className="font-black italic uppercase text-sm mb-2 text-[#FF3333]">{t('settings.danger.title')}</h2><p className="text-xs text-gray-400 mb-4">{t('settings.danger.leaveDescription')}</p><button onClick={onLeave} disabled={disabled} className="w-full border border-[#FF3333] text-[#FF3333] py-3 rounded-2xl font-black italic text-xs uppercase">{t('settings.danger.leave')}</button></section>; }
function State({ label }) { return <div className="min-h-screen bg-[#0A0E2A] text-white flex items-center justify-center font-sans"><p className="text-xs font-black uppercase opacity-40 animate-pulse">{label}</p></div>; }
