import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import BottomNav from '../components/layout/BottomNav';
import { getCurrentUser } from '../services/authService';
import { getUserLeagueDetails } from '../services/leagueService';
import { getWhatIfScenario } from '../services/whatifService';
import { getNhlTeamMetadata, getWorldCupGroup, NHL_CONFERENCES, NHL_DIVISIONS, WORLD_CUP_GROUP_IDS } from '../config/whatif';

const sortTeams = (teams) => [...teams].sort((a, b) => b.points - a.points || b.wins - a.wins || b.goalDifference - a.goalDifference);

export default function WhatIf() {
  const { ligaId } = useParams(); const navigate = useNavigate(); const { t } = useTranslation();
  const [league, setLeague] = useState(null); const [teams, setTeams] = useState([]); const [conference, setConference] = useState('all'); const [division, setDivision] = useState('all'); const [group, setGroup] = useState('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const isFootball = league?.sportId === 1; const isWorldCup = league?.officialLeagueId === 12;
  useEffect(() => { if (!ligaId) return; const load = async () => { setLoading(true); setError(false); try { const [user, userLeague] = await Promise.all([getCurrentUser(), getUserLeagueDetails(ligaId)]); if (!user) { navigate('/'); return; } const scenario = await getWhatIfScenario({ userId: user.id, userLeagueId: userLeague.id, officialLeagueId: userLeague.officialLeagueId }); setLeague(userLeague); setTeams(buildTeams(scenario)); } catch (loadError) { console.error('Unable to load what-if scenario', loadError); setError(true); } finally { setLoading(false); } }; load(); }, [ligaId, navigate]);
  const visibleTeams = useMemo(() => sortTeams(teams.filter((team) => (!isFootball ? (conference === 'all' || team.conference === conference) && (division === 'all' || team.division === division) : !isWorldCup || group === 'all' || team.group === group))), [teams, isFootball, isWorldCup, conference, division, group]);
  if (loading) return <State label={t('whatIf.loading')} />;
  if (error || !league) return <State label={t('whatIf.messages.loadError')} />;
  return <div className="min-h-screen bg-[#0A0E2A] text-white p-4 font-sans pb-40 overflow-x-hidden"><header className="max-w-7xl mx-auto flex justify-between items-center mb-6"><button onClick={() => navigate(league.sportId ? `/leagues/${league.sportId}` : '/home')} className="bg-[#1A1C3A] text-white px-5 py-2 rounded-2xl text-[10px] font-black border border-[#26283A]">← {t('common.back')}</button><div className="text-right"><h1 className="text-xl font-black italic text-[#0077FF] uppercase tracking-tighter leading-none">{t('whatIf.title')}</h1><span className="text-[9px] font-black text-gray-400 uppercase tracking-wider block mt-1">{league.name}</span></div></header>{!isFootball && <NhlFilters conference={conference} division={division} setConference={setConference} setDivision={setDivision} t={t} />}{isWorldCup && <WorldCupFilter group={group} setGroup={setGroup} t={t} />}<StandingsTable teams={visibleTeams} isFootball={isFootball} isWorldCup={isWorldCup} t={t} /><BottomNav /></div>;
}
function buildTeams({ stats, teams, matches }) { const teamById = Object.fromEntries(teams.map((team) => [team.id, team])); const matchesByTeam = matches.reduce((count, match) => { count[match.home_team_id] = (count[match.home_team_id] ?? 0) + 1; count[match.away_team_id] = (count[match.away_team_id] ?? 0) + 1; return count; }, {}); return stats.map((row) => { const team = teamById[row.team_id] ?? {}; const nhl = getNhlTeamMetadata(team.name); return { id: row.team_id, name: team.name ?? 'Unknown', logo: team.url_logo, games: row.jogos, wins: row.w, draws: row.d, losses: row.l, points: row.pts, pointsPercentage: row.jogos > 0 ? (row.pts / (row.jogos * 2)).toFixed(2) : '0.00', goalsFor: row.gf, goalsAgainst: row.ga, goalDifference: row.diff, correctWins: row.acerto_v, correctDraws: row.acerto_e, correctLosses: row.acerto_d, correctGoals: row.acerto_gols, exact: row.cravada, withoutPrediction: Math.max(0, (matchesByTeam[row.team_id] ?? 38) - row.jogos), conference: nhl.conference, division: nhl.division, group: getWorldCupGroup(row.team_id) }; }); }
function NhlFilters({ conference, division, setConference, setDivision, t }) { return <div className="max-w-7xl mx-auto grid grid-cols-2 gap-4 mb-6 bg-[#1A1C3A] p-4 rounded-[25px] border border-[#26283A]"><Select label={t('whatIf.conference')} value={conference} setValue={setConference} options={NHL_CONFERENCES} prefix="whatIf.conferences" t={t} /><Select label={t('whatIf.division')} value={division} setValue={setDivision} options={NHL_DIVISIONS} prefix="whatIf.divisions" t={t} /></div>; }
function WorldCupFilter({ group, setGroup, t }) { return <div className="max-w-7xl mx-auto mb-6 bg-[#1A1C3A] p-4 rounded-[25px] border border-[#26283A]"><Select label={t('whatIf.group')} value={group} setValue={setGroup} options={WORLD_CUP_GROUP_IDS} prefix="whatIf.groups" t={t} /></div>; }
function Select({ label, value, setValue, options, prefix, t }) { return <div><label className="block text-[8px] font-black uppercase text-gray-400 mb-2 pl-1">{label}</label><select value={value} onChange={(event) => setValue(event.target.value)} className="w-full bg-[#0A0E2A] border border-[#26283A] text-xs font-bold rounded-xl p-3 outline-none text-white"><option value="all">{t('whatIf.all')}</option>{options.map((option) => <option key={option} value={option}>{t(`${prefix}.${option}`, { defaultValue: option })}</option>)}</select></div>; }
function StandingsTable({ teams, isFootball, isWorldCup, t }) { const headers = [['games', 'games'], ['wins', 'wins'], [isFootball ? 'draws' : 'otl', isFootball ? 'draws' : 'otl'], ['losses', 'losses'], ['points', 'points'], ...(!isFootball ? [['percentage', 'pointsPercentage']] : []), ['goalsFor', 'goalsFor'], ['goalsAgainst', 'goalsAgainst'], ['difference', 'goalDifference'], ['correctWins', 'correctWins'], ...(isFootball ? [['correctDraws', 'correctDraws']] : []), ['correctLosses', 'correctLosses'], ['correctGoals', 'correctGoals'], ['exact', 'exact'], ['withoutPrediction', 'withoutPrediction']]; return <div className="max-w-7xl mx-auto bg-[#1A1C3A] border border-[#26283A] rounded-[35px] shadow-2xl overflow-hidden"><div className="overflow-x-auto custom-scrollbar"><table className="w-full text-left border-collapse min-w-[1100px]"><thead><tr className="bg-[#0A0E2A] border-b border-[#26283A] text-gray-400 text-[9px] font-black uppercase italic"><th className="py-4 pl-6 text-center">{t('whatIf.table.position')}</th><th className="py-4 pl-4">{t('whatIf.table.team')}</th>{isWorldCup && <th className="py-4 text-center">{t('whatIf.table.group')}</th>}{headers.map(([label]) => <th key={label} className="py-4 text-center">{t(`whatIf.table.${label}`)}</th>)}</tr></thead><tbody className="divide-y divide-[#26283A] text-xs font-bold">{teams.map((team, index) => <tr key={team.id} className="hover:bg-[#0A0E2A]/40"><td className="py-4 pl-6 text-center text-gray-500">{index + 1}º</td><td className="py-4 pl-4 flex items-center gap-3"><img src={team.logo} className="w-6 h-6 object-contain" alt="" /><span className="uppercase truncate text-white">{team.name}</span></td>{isWorldCup && <td className="py-4 text-center">{t(`whatIf.groups.${team.group}`, { defaultValue: team.group })}</td>}{headers.map(([label, property]) => <td key={label} className={`py-4 text-center ${label === 'points' ? 'font-black text-[#0077FF]' : ''}`}>{property === 'goalDifference' && team[property] > 0 ? `+${team[property]}` : team[property]}</td>)}</tr>)}</tbody></table></div></div>; }
function State({ label }) { return <div className="min-h-screen bg-[#0A0E2A] text-[#0077FF] flex items-center justify-center font-black animate-pulse tracking-widest">{label}</div>; }
